### ISSUE TITLE
Update web_socket_channel dependency

### ISSUE THREAD

**Issue by ahmed-tarek-salem** [reown-com/reown_flutter#10]
**Is your feature request related to a problem? Please describe.**  
I'm experiencing a dependency conflict in my Flutter project when trying to use `reown_walletkit ^1.0.0` alongside `share_plus ^10.0.2`. The conflict arises due to incompatible versions of the `web` package required by `web_socket_channel` from `reown_walletkit` and `share_plus`.

**Error:**
```
Resolving dependencies...
Because no versions of share_plus match >10.0.2 <11.0.0 and share_plus 10.0.2 depends on web ^1.0.0, share_plus ^10.0.2 requires web ^1.0.0.
And because web_socket_channel >=2.4.4 <3.0.1 depends on web ^0.5.0, share_plus ^10.0.2 is incompatible with web_socket_channel >=2.4.4 <3.0.1.
And because every version of reown_walletkit depends on reown_core ^1.0.0 which depends on web_socket_channel ^2.4.4, share_plus ^10.0.2 is incompatible with reown_walletkit.
So, because my_project depends on both share_plus ^10.0.2 and reown_walletkit ^1.0.0, version solving failed.
```

**Describe the solution you'd like:**  
It would be helpful to update the web_socket_channel dependency to >=2.4.4 <3.0.1 or any version that supports web: ^1.0.0, which resolves this conflict.

**Describe alternatives you've considered:**  
For now, I am using a dependency override:  
```yaml
dependency_overrides:
  web_socket_channel: ^3.0.0
```
However, this might lead to runtime issues, so a proper update would be preferred.

**Comment by quetool** [comment]
Hello @ahmed-tarek-salem ! Thanks for opening, using dependency override it's the right solution right now IMHO. I'll be upgrading all dependencies ASAP anyway.

**Comment by quetool** [comment]
@ahmed-tarek-salem  major decency upgrades are going to be held during our tech debt week, which should happen before EOY

**Comment by dincollu** [comment]
hi @quetool, are there any news about the dependency upgrades?

**Comment by quetool** [comment]
Hi @dincollu ! We are planning to upgrade to latest flutter version and update dependencies during our tech debt week coming next week!
