### ISSUE TITLE
Type Logger not found

### ISSUE THREAD

**Issue by MohammadUzair1** [reown-com/reown_flutter#16]
**Describe the bug**
../../../.pub-cache/hosted/pub.dev/reown_appkit-1.0.1/lib/modal/appkit_modal_impl.dart:116:3: Error: Type 'Logger' not found.
  Logger get _logger => _appKit.core.logger;

**To Reproduce**
1. Running app on iOS simulator iOS version 18.0
2. Click on run without debugging
3. See error
<img width="695" alt="Screenshot 2024-10-14 at 4 16 30 PM" src="https://github.com/user-attachments/assets/e273a085-1142-4a1f-b02d-3f4236d05697">

**Comment by quetool** [comment]
Hello @MohammadUzair1! It has been fixed in the latest beta https://pub.dev/packages/reown_appkit/versions/1.1.0-beta01

Do you mind updating to that one and let me know? Beta is only for social login, everything else is not affected.

**Comment by MohammadUzair1** [comment]
Thanks!
