### ISSUE TITLE
Build fails due to missing Logger import in app_kit_modal_impl.dart

### ISSUE THREAD

**Issue by vitalii-petrun** [reown-com/reown_flutter#24]
**Describe the bug**

File `app_kit_modal_impl.dart` uses the `Logger` class, but the `Logger` type is not imported, leading to a compilation error.

**Expected behavior**: The build should succeed  
**Actual behavior**: The build fails with an error indicating that the `Logger` type cannot be found.

**To Reproduce**

1. Place `reown_appkit: ^1.0.1` in pubspec.yaml
2. `import 'package:reown_appkit/reown_appkit.dart';` somewhere
3. Run the build.

**Additional context**

Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
/C:/Users/vitalii/AppData/Local/Pub/Cache/hosted/pub.dev/reown_appkit-1.0.1/lib/modal/appkit_modal_impl.dart:116:3: Error: Type 'Logger' not found.
  Logger get _logger => _appKit.core.logger;
  ^^^^^^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'E:\SDKs\flutter\bin\flutter.bat'' finished with non-zero exit value 1

BUILD FAILED in 8s
Error: Gradle task assembleDebug failed with exit code 1

**Comment by vitalii-petrun** [comment]
flutter doctor -v
[√] Flutter (Channel stable, 3.22.3, on Microsoft Windows [Version 10.0.22631.4317], locale en-US)
    • Flutter version 3.22.3 on channel stable at E:\SDKs\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (3 months ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at E:\SDKs\android
    • Platform android-35, build-tools 35.0.0
    • Java binary at: E:\Apps\AndroidStudio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.11.35222.181
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2024.1)
    • Android Studio at E:\Apps\AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 15 (API 35) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22631.4317]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 129.0.6668.72
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 129.0.2792.89

[√] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by quetool** [comment]
Yes, it's fixed in latest beta, which should be promoted to stable soon

**Comment by obumnwabude** [comment]
Turns out that allowing pub to figure out the version to be installed auto causes this error. Like if you just run `flutter pub add reown_appkit`, you get this error when you build flutter.

**Comment by ismail-mufin** [comment]
@quetool when it will be promoted to stable? thanks

**Comment by quetool** [comment]
> Turns out that allowing pub to figure out the version to be installed auto causes this error. Like if you just run `flutter pub add reown_appkit`, you get this error when you build flutter.

@obumnwabude this is because flutter pub install stable version and this is fixed in beta.

@ismail-mufin hopefully this week!

**Comment by quetool** [comment]
Hello, version 1.2.0 is out in stable!
