### ISSUE TITLE
`package:web` conflict when using both `reown_walletkit` and `flutter_inappwebview`

### ISSUE THREAD

**Issue by AlexV525** [reown-com/reown_flutter#27]
**Describe the bug**

```console
Because every version of flutter_inappwebview from git depends on flutter_inappwebview_web ^1.1.2 which depends on web ^1.0.0, every version of flutter_inappwebview from git requires web ^1.0.0.
And because web_socket_channel 2.4.5 depends on web ^0.5.0, flutter_inappwebview from git is incompatible with web_socket_channel 2.4.5.
And because no versions of web_socket_channel match >2.4.5 <3.0.0 and reown_core 1.0.2 depends on web_socket_channel ^2.4.5, flutter_inappwebview from git is incompatible with reown_core 1.0.2.
Because reown_walletkit 1.0.2 depends on reown_core ^1.0.2 and no versions of reown_core match >1.0.2 <2.0.0, reown_walletkit 1.0.2 requires reown_core 1.0.2.
Thus, flutter_inappwebview from git is incompatible with reown_walletkit 1.0.2.
So, because flutter_project depends on both reown_walletkit 1.0.2 and flutter_inappwebview from git, version solving failed.
```

**To Reproduce**

```yaml
dependencies:
  flutter_inappwebview: ^6.1.0
  reown_walletkit: ^1.0.2
```

**Additional context**
```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.7 23H124 darwin-arm64 (Rosetta), locale en-US)
```

**Comment by tungakanui** [comment]
I have a similar issue, but with the firebase
`    Because firebase_core >=3.5.0 depends on firebase_core_web ^2.18.1 which depends on web ^1.0.0, firebase_core >=3.5.0 requires web ^1.0.0.
(1) So, because web_socket_channel >=2.4.4 <3.0.1 depends on web ^0.5.0, firebase_core >=3.5.0 is incompatible with web_socket_channel >=2.4.4 <3.0.1.

    Because reown_appkit >=1.2.0-alpha01 depends on reown_core ^1.0.2 and reown_appkit >=1.1.0-beta01 <1.2.0-alpha01 depends on reown_core ^1.0.1,
      reown_appkit >=1.1.0-beta01 requires reown_core ^1.0.1.
    And because reown_appkit <1.1.0-beta01 depends on reown_core ^1.0.0, every version of reown_appkit requires reown_core ^1.0.0.
    And because reown_core <1.0.1 depends on web_socket_channel ^2.4.4 and reown_core >=1.0.1 depends on web_socket_channel ^2.4.5, every version of
      reown_appkit requires web_socket_channel ^2.4.4.
    And because firebase_core >=3.5.0 is incompatible with web_socket_channel >=2.4.4 <3.0.1 (1), firebase_core >=3.5.0 is incompatible with reown_appkit.       
    So, because stuntland depends on both firebase_core ^3.6.0 and reown_appkit any, version solving failed.
`

**Comment by ToanBarcelona1998** [comment]
Try downgrading the version of the webview package. This seems to be a common problem when you work with Flutter.

**Comment by rezaei-ali-82** [comment]
use 
dependency:
  flutter_inappwebview: ^6.0.0
  reown_walletkit: ^1.0.3
dependency_overrides:
  webview_flutter_android: 3.16.1

**Comment by quetool** [comment]
Hello here! This should not be an issue anymore in latest beta published yesterday, can you all check?

AppKit: https://pub.dev/packages/reown_appkit/versions/1.3.0-beta01/changelog
WalletKit: https://pub.dev/packages/reown_walletkit/versions/1.1.0-beta01/changelog

**Comment by AlexV525** [comment]
> ```yaml
> dependencies:
>   flutter_inappwebview: ^6.1.0
>   reown_walletkit: ^1.0.2
> ```

I can confirm this is now working. Closing as resolved.
