### ISSUE TITLE
ethSendTransaction is not working properly

### ISSUE THREAD

**Issue by damienissa** [reown-com/reown_flutter#29]
**Describe the bug**

I am trying to send BNB via AppKit using the Binance Smart Chain Testnet. The transaction is created, and I receive a hash, but there is no information visible on [BscScan Testnet](https://testnet.bscscan.com/). When using MetaMask’s dev portal example, the transaction works as expected.

**To Reproduce**

Use the following MetaMask code to send BNB:
```javascript
await window.ethereum.request({
  "method": "eth_sendTransaction",
  "params": [
    {
      to: "0x33d23FFeBf69F9e655Ac869415F86e8605127CF3",
      from: "0x4b167dd39f15f4485782ece04cd30a4a6654831f",
      gas: "0x76c0",
      value: "0x16345785d8a0000",
      data: "0x",
      gasPrice: "0x4a817c800"
    }
  ],
});
```
Attempt to send BNB using the provided Dart code via AppKit.
Observe that a transaction hash is generated, but no transaction is visible on BscScan Testnet.
Expected behavior

The transaction should be reflected on [BscScan Testnet](https://testnet.bscscan.com/) as it is when using the MetaMask example.

Reproducible code

Here is the Dart code used in the AppKit implementation:

```dart
String _bnbToHex(double amount) {
  // Convert BNB to wei
  BigInt weiAmount = BigInt.from(amount * 1e18);
  // Convert to hex string
  return '0x${weiAmount.toRadixString(16)}';
}
```
```dart
try {
  // Define the recipient address and the amount to send
  const recipientAddress = '0x33d23FFeBf69F9e655Ac869415F86e8605127CF3';
  final amountToSend = _bnbToHex(0.2);

  final params = {
    'to': recipientAddress,
    'from': _appKitModal.session!.getAddress(NetworkUtils.eip155),
    'gas': '0x76c0',
    'value': amountToSend,
    'data': '0x',
    'gasPrice': '0x4a817c800',
  };

  // Ensure the wallet is launched before sending the transaction
  _appKitModal.launchConnectedWallet();

  // Send the transaction using eth_sendTransaction RPC call
  final result = await _appKitModal.request(
    topic: _appKitModal.session!.topic,
    chainId: _appKitModal.selectedChain!.chainId,
    request: SessionRequestParams(
      method: MethodsConstants.ethSendTransaction,
      params: [params],
    ),
  );

  // Check the result
  if (result != null) {
    print('Transaction successful! TxHash: $result');
  } else {
    print('Transaction failed.');
  }
} catch (error) {
  print('Error sending BNB: $error');
}
```

The transaction works as expected using MetaMask, but fails to appear on the BscScan Testnet when using AppKit. It seems like there might be a difference in how the transaction is being sent or processed.

**Comment by Dappsnode** [comment]
@damienissa It looks like you’re experiencing an issue where your transaction is not appearing on BscScan Testnet despite receiving a transaction hash. Since the MetaMask example works as expected, the issue might lie within the Dart code or the way AppKit handles the transaction.

**Comment by damienissa** [comment]
@Dappsnode For sure! But I do not understand where the problem is. Can you please help me to find an issue?

**Comment by Dappsnode** [comment]
@damienissa 
 Ensure that both MetaMask and AppKit are connected to the Binance Smart Chain Testnet. Make sure that the parameters used in the Dart code match those in the MetaMask example, especially the gas, gasPrice, and value.

**Comment by damienissa** [comment]
@Dappsnode Both are connected to chain ID: 97 which is the ID of BSC Testnet. Gas, gas price, and value are copy-pasted from the metaMask example. Also, I see transactions in my MetaMask app. But no updates on the BSC scan![image](https://github.com/user-attachments/assets/62dcfad4-c5a9-4b82-b3ae-150a169e65fb)

**Comment by quetool** [comment]
Hello @damienissa! I'll be taking a look ASAP!

**Comment by damienissa** [comment]
@quetool Thanks!

**Comment by damienissa** [comment]
@quetool Any ideas so far?

**Comment by quetool** [comment]
Hello @damienissa seems like you are using `1.2.0-alpha01` version, is that correct? If so, please switch to `1.1.0-beta02` and try the following:

```dart
return await _appKitModal.request(
  topic: _appKitModal.session!.topic,
  chainId: _appKitModal.selectedChain!.chainId,
  request: SessionRequestParams(
    method: 'eth_sendTransaction',
    params: [
      Transaction(
        from: EthereumAddress.fromHex(_appKitModal.session!.address!),
        to: EthereumAddress.fromHex(
            '0x33d23FFeBf69F9e655Ac869415F86e8605127CF3'),
        // value: EtherAmount.fromInt(EtherUnit.finney, 12), // == 0.012
        // gasPrice:
        // data:
        // etc....
      ).toJson(),
    ],
  ),
);
```

Of course BSC Testnet has to be selected otherwise you can just pass the chainId `chainId: 'eip155:97',`.

Let me know.

**Comment by damienissa** [comment]
@quetool Not help!
![image](https://github.com/user-attachments/assets/6dcf93c9-22f0-4e12-aeb1-fe26d44b6603)


<img width="672" alt="image" src="https://github.com/user-attachments/assets/014012fd-94c2-4b59-9dba-bd43d0bba981">

My current code:
```dart
try {
      // Define the recipient address and the amount to send
      const recipientAddress = '0x33d23FFeBf69F9e655Ac869415F86e8605127CF3';
      // final amountToSend = _bnbToHex(0.2);

      // final params = {
      //   'to': recipientAddress,
      //   'from': _appKitModal.session!.getAddress(NetworkUtils.eip155),
      //   'gas': '0x76c0',
      //   'value': amountToSend,
      //   'data': '0x',
      //   'gasPrice': '0x4a817c800',
      // };
      // Ensure the wallet is launched before sending the transaction
      // _appKitModal.launchConnectedWallet();
      // Set gas price and gas limit
      final gasPrice = EtherAmount.inWei(BigInt.from(25000000000)); // 25 Gwei
      const gasLimit = 21000; // Stand

      // Send the transaction using eth_sendTransaction RPC call
      final result = await _appKitModal.request(
        topic: _appKitModal.session!.topic,
        chainId: _appKitModal.selectedChain!.chainId,
        request: SessionRequestParams(
          method: MethodsConstants.ethSendTransaction,
          params: [
            Transaction(
              from: EthereumAddress.fromHex(
                  _appKitModal.session!.getAddress(NetworkUtils.eip155) ?? ''),
              to: EthereumAddress.fromHex(recipientAddress),
              value: EtherAmount.fromInt(EtherUnit.finney, 12), // == 0.012
              gasPrice: gasPrice,
              maxGas: gasLimit,
              // data:
              // etc....
            ).toJson(),
          ],
        ),
      );

      // Check the result
      if (result != null) {
        print('Transaction successful! TxHash: $result');
      } else {
        print('Transaction failed.');
      }
    } catch (error) {
      print('Error sending BNB: $error');
    }
```

**Comment by quetool** [comment]
According to this code of you are still on `1.2.0-alpha01`, please switch first to `1.1.0-beta02`:

```
reown_appkit: ^1.1.0-beta02
```

**Comment by quetool** [comment]
After that, please try this simple transaction as params:

```dart
Transaction(
  from: EthereumAddress.fromHex(appKitModal.session!.address!),
  to: EthereumAddress.fromHex(recipientAddress),
  value: EtherAmount.fromInt(EtherUnit.finney, 12),
).toJson(),
```

**Comment by damienissa** [comment]
I'm on `reown_appkit: ^1.1.0-beta02` for sure

But if I'll use your code I'll see an error:
```bash
The getter 'address' isn't defined for the type 'ReownAppKitModalSession'.
Try importing the library that defines 'address', correcting the name to the name of an existing getter, or defining a getter or field named 'address'
```

**Comment by quetool** [comment]
I'm struggling receiving tBNB from faucets, if you could send me some to `0x59e2f66C0E96803206B6486cDb39029abAE834c0` I'll appreciate. Otherwise I can't test much for now. All I can say is that everything seems to be fine on our SDK seems Metamask does show the approval modal with the correct value.

**Comment by damienissa** [comment]
Result the same. 
Dart code: 
```dart
try {
      // Define the recipient address and the amount to send
      const recipientAddress = '0x33d23FFeBf69F9e655Ac869415F86e8605127CF3';
      // Set gas price and gas limit
      final gasPrice = EtherAmount.inWei(BigInt.from(25000000000)); // 25 Gwei
      const gasLimit = 21000; // Stand

      // Send the transaction using eth_sendTransaction RPC call
      final result = await _appKitModal.request(
        topic: _appKitModal.session!.topic,
        chainId: _appKitModal.selectedChain!.chainId,
        request: SessionRequestParams(
          method: MethodsConstants.ethSendTransaction,
          params: [
            Transaction(
              from: EthereumAddress.fromHex(_appKitModal.session!.address!),
              to: EthereumAddress.fromHex(recipientAddress),
              value: EtherAmount.fromInt(EtherUnit.finney, 12),
            ).toJson(),
            // ).toJson(),
          ],
        ),
      );

      // Check the result
      if (result != null) {
        print('Transaction successful! TxHash: $result');
      } else {
        print('Transaction failed.');
      }
    } catch (error) {
      print('Error sending BNB: $error');
    }
```
Output:
`flutter: Transaction successful! TxHash: 0x40d0602bf5465ae027eada60d8f13652ab6775ea3595204bfe2e0c6ab433055b`

BSC Scan Testnet:
<img width="1458" alt="image" src="https://github.com/user-attachments/assets/dbc9dfd2-de62-4140-b880-19da529e0740">

MetaMask app:
![image](https://github.com/user-attachments/assets/54bbe67b-404c-4259-b2aa-3aea7f935a0c)

**Comment by damienissa** [comment]
@quetool I sent you 1 tBNB for a test. In my case, it's still not working.

**Comment by quetool** [comment]
Hello @damienissa! It's working really fine to me! Here's the hash https://testnet.bscscan.com/tx/0x663a0cbbcab6c01a65fcaf55ac2416ab512cb4d942022f0cc102020f024c1399

![Simulator Screenshot - iPhone 13 mini - 2024-10-28 at 15 40 07](https://github.com/user-attachments/assets/ce028dfb-534e-4258-bec8-7a677efc5ef7)


I'll send you now the whole tBNB balance, give me a few minutes

**Comment by quetool** [comment]
Here's the remaining balance I sent back to you from our test dapp: https://testnet.bscscan.com/tx/0xae6a302076365d19a98437f228d18675ba2b90ce60dbce24c12d0f1a2df9213f

<img src="https://github.com/user-attachments/assets/aa63d9b5-9531-4f75-8384-1be0e916a6d0" width="300">

If you want you can share your full code and I can try fix it.

**Comment by damienissa** [comment]
@quetool See it on my balance. Can you please share the full code with me?

**Comment by quetool** [comment]
It's our example dapp's code inside `reown_flutter/packages/reown_appkit/example/modal` https://github.com/reown-com/reown_flutter/blob/develop/packages/reown_appkit/example/modal/lib/services/eip155_service.dart#L102

Same code as I shared to you earlier. You can clone this repo and try it out directly.

You can also try this just in case:

```dart
final result = await _appKitModal.request(
        topic: _appKitModal.session!.topic,
        chainId: 'eip155:97',
        request: SessionRequestParams(
          method: 'eth_sendTransaction',
          params: [
            Transaction(
              from: EthereumAddress.fromHex(_appKitModal.session!.address!),
              to: EthereumAddress.fromHex(recipientAddress),
              value: EtherAmount.fromInt(EtherUnit.finney, 12),
              data: utf8.encode('0x'), // to make it work with some wallets
            ).toJson(),
          ],
        ),
      );
```

**Comment by damienissa** [comment]
I downloaded the code, added my project ID and replace `receiverAddress` to mine. And the result is the same:
TX: 0x82b53a735c9e70bc0c82a085ad46150dbb1fb2fec3877dd62b8f443193012d38
![image](https://github.com/user-attachments/assets/3039e2eb-769d-4f21-bf99-028bbdc8458d)

**Comment by damienissa** [comment]
@quetool  Maybe I need to add some additional settings in my project?
<img width="1023" alt="image" src="https://github.com/user-attachments/assets/d8a5df3e-d1d4-47d8-90c7-287cf710c9c8">

**Comment by quetool** [comment]
> @quetool Maybe I need to add some additional settings in my project?

Nope, this is just a simple RPC request. I just sent to myself my dust balance of tBNB and it went through... https://testnet.bscscan.com/tx/0x54164bad3b41d55fc680cf9e4374dd978139267f0950ecfb5b61d8095ec7484d

It's really weird, allow me some time to ask to the team.

**Comment by damienissa** [comment]
@quetool Take your time. I want to say that it's amazing lib and you are doing a great job!

**Comment by quetool** [comment]
Thanks for the feedback @damienissa ! 
Final question (for now): Can you share your BSC Testnet data and how you add it to appkit?

**Comment by damienissa** [comment]
@quetool It looks like it was some issue in MetaMask. I removed the app, install it again, setup BSC Testnet and try to create a new transaction and it works fine. Sorry for spending your time. Issue resolved!

**Comment by quetool** [comment]
Nothing to be sorry about at this might be useful for other devs! Hint: When it comest to metamask it's better if you add `extraRpcUrls: []` in the `ReownAppKitModalNetworkInfo` object as some times Metamask can not find the RPC Url given as default.

I'll close this issue then! Thanks!
