### ISSUE TITLE
Relay connect failure in beta releases. Missing Logger on stable releases.

### ISSUE THREAD

**Issue by haykgalstyan** [reown-com/reown_flutter#36]
**Describe the bug**

Hello. I get relay connection error on the newer beta releases:
[RelayClient], _connect error: SocketException: Failed host lookup: 'relay.walletconnect.org' (OS Error: No address associated with hostname, errno = 7)

And I cannot use stable cause there I get compile error on missing Logger class

**To Reproduce**
Try to connect a wallet on android. (Pixel 8, latest public android version)

<img width="1576" alt="image" src="https://github.com/user-attachments/assets/05b3a9e4-16c5-421e-a7dd-631dc61795db">

**Comment by quetool** [comment]
Hello @haykgalstyan! `SocketException: Failed host lookup: 'relay.walletconnect.org' (OS Error: No address associated with hostname, errno = 7)` is usually related to not having connectivity in the device. In fact that error is coming from `http` package and not from `AppKit`. Can you please confirm you have Internet access in the device?
