### ISSUE TITLE
Apple signin does not populate email address (used to work)

### ISSUE THREAD

**Issue by rhamnett** [reown-com/reown_flutter#37]
**Describe the bug**

I am using develop commit 2260cd61c339d384c61ae6f35f0f898aa535b1af (latest at time of posting)

Signing in with apple on the modal appkit example does not show the email.

I can however successfully print the email from the current session

Also disconnect it totally broken almost every time.

**To Reproduce**

1. Sign in with apple
2 Click the wallt info button
3 Email is missing (see picture)

**Expected behavior**

Email populated in correct box

**Reproducible code**

Unaltered modal appkit wallet example from source tree

**Screenshots**

<img width="420" alt="Screenshot 2024-11-19 at 13 21 38" src="https://github.com/user-attachments/assets/9f623318-eb03-4168-80aa-154ace8b7103">

**Smartphone (please complete the following information):**

 - Device:  ios simulator 17.0

**Comment by rhamnett** [comment]
Please also note, trying to change network causes the login with Apple to pop open again

**Comment by quetool** [comment]
Hello @rhamnett, thanks for sharing, can you confirm that you can however perform signing actions like `personal_sign`? Do you mind sharing a full demo video as this is the first time someone reports this issue?

> Please also note, trying to change network causes the login with Apple to pop open again

Regarding this, it is the expected behavior if you have SIWE enabled with `signOutOnNetworkChange` https://docs.reown.com/appkit/flutter/core/siwe#siweconfig-reference

**Comment by rhamnett** [comment]
Hello signOutOnNetworkChange is already set to false, i have used your modal appkit example code.


https://github.com/user-attachments/assets/dffb18e7-53c8-4970-bae8-7137dd1dfb1e

**Comment by rhamnett** [comment]
FYI disconnect is failing on regular linked wallets like metamask etc

**Comment by quetool** [comment]
Thanks for the video, allow me some time to investigate!

**Comment by quetool** [comment]
Can you check if the same is happening here? https://appkit-lab.reown.com/library/wagmi/

**Comment by rhamnett** [comment]
@quetool  on that site, it shows the apple email in the correct box and disconnects

**Comment by quetool** [comment]
Steps to repro would be fine. Did you just clone our repo and ran `/base/` example?

**Comment by rhamnett** [comment]
As mentioned earlier, I just took the base of /modal/ not base example.

I dont really have and steps to reproduce, i can give you access to my forked version?

**Comment by rhamnett** [comment]
@quetool you should have an invite to my repo

**Comment by rhamnett** [comment]
Thank you, if it helps, some of these issues seemed to have started around the time your changes to make:

```
 final address = _appKitModal.session!.address
```

to 

```
      final chainId = _appKitModal.selectedChain?.chainId ?? '1';
      final namespace = ReownAppKitModalNetworks.getNamespaceForChainId(
        chainId,
      );
      final address = _appKitModal.session!.getAddress(namespace)!;
```

I am not sure if this is a red herring or useful to you.

**Comment by quetool** [comment]
Could have been introduced in that PR but is not related. I have already identified the issue and testing out a fix for issues 1 and 3.

**Comment by quetool** [comment]
Hello @rhamnett I can not try out your project as I get the relay closed due to `Unauthorized: origin not allowed`. This happens if you whitelisted specific bundleIds.

**Comment by quetool** [comment]
Hello @rhamnett, the reason why disconnect is failing is because you are hiding `AppKitModalConnectButton()` once the DApp is connected [on line 803](https://github.com/rhamnett/reown_flutter/blob/develop/packages/reown_appkit/example/modal/lib/home_page.dart#L803). You shouldn't do that, check the NOTE here in the docs: https://docs.reown.com/appkit/flutter/core/email#options

**Comment by rhamnett** [comment]
@quetool  my apologies, i had totally missed this. Thanks for the assistance. Shall we keep this ticket open to wait for the Apple fixes?

**Comment by rhamnett** [comment]
@quetool Another quick one. 

If you pull my branch, you will see that the text in the button is correctly set to the walltet address, if i log in via email/social but is "null" when logging in via another wallet on the device using walletconnect

```
 child: appKit.isConnected
                  ? Text(
                      '${appKit.session!.getAddress(appKit.selectedChain?.chainId ?? '1')?.substring(0, 7)}...')
                  : const Text('Get loyalty offers'),
```

Can you kindly advise?

**Comment by quetool** [comment]
Yes please, let's keep it open

**Comment by quetool** [comment]
Hello @rhamnett! This is now fixed on latest beta https://pub.dev/packages/reown_appkit/versions/1.2.0-beta02
Thanks for reporting!

**Comment by rhamnett** [comment]
Thanks I can confirm this fixed the issue @quetool
