### ISSUE TITLE
Various social login options are missing

### ISSUE THREAD

**Issue by rhamnett** [reown-com/reown_flutter#44]
**Describe the bug**

Hello! Google (probably the most important) and various other login options are missing from appkit examples, but are present on react example.

This should really be implemented as a default. 

https://github.com/reown-com/reown_flutter/blob/develop/packages/reown_appkit/lib/modal/models/public/appkit_social_options.dart

**To Reproduce**

1. Launch appkit modal demo
2. No google/github etc option

**Expected behavior**

Have a complete option, to log-in va google and other social options.

**Reproducible code**

See https://github.com/reown-com/reown_flutter/tree/develop/packages/reown_appkit/example/modal/

Thanks and keep up the great work!
Rich

**Comment by quetool** [comment]
Hello @rhamnett! We are still working on Google, Facebook and a few more on native plaforms as we are enhancing the security for those services. I don't have an ETA but for sure we are gonna add them.
