### ISSUE TITLE
How To do tron_signTransaction add wallet kit?

### ISSUE THREAD

**Issue by YerikhoSt** [reown-com/reown_flutter#56]
<img width="592" alt="Screenshot 2024-12-13 at 09 59 09" src="https://github.com/user-attachments/assets/df8a3d01-6d6d-4f4f-aa9a-3b756b42d7c0" />

**Comment by quetool** [comment]
Hello @YerikhoSt, can you share your testing case? The screenshot you are sharing looks like the React App and not Flutter Example project 🤔

**Comment by quetool** [comment]
Hello @YerikhoSt, there's a Tron example in this PR. Let me know if need help https://github.com/reown-com/reown_flutter/pull/60/files
