### ISSUE TITLE
JsonRpcError(code: null, message: null)

### ISSUE THREAD

**Issue by nuzhata** [reown-com/reown_flutter#61]
reown_appkit-1.2.0/example/modal:

Show error JsonRpcError(code: null, message: null) when you want to connect to MetaMask wallet after opening wallet
errors_patch.dart line 27

When you want to connect with reown_appkit-1.2.0/example/base to MetaMask wallet it doesn't show any error or connection request

**Comment by quetool** [comment]
Hello @nuzhata! Do you need more help here or can it be closed?

**Comment by nuzhata** [comment]
It can be closed.
