### ISSUE TITLE
Solflare wallet not shown in wallet list

### ISSUE THREAD

**Issue by haykgalstyan** [reown-com/reown_flutter#69]
Both on iOS and android, seemingly independent of any configurations solflare wallet is not shown in the list. I have added the package to android manifest and iOS info.plist and tried many different ways of initializing the wallet.
Please let me know if I can help in any way to reproduce.

<img width="320" alt="image" src="https://github.com/user-attachments/assets/6fab1e8d-df3e-495e-9ecf-b493d4bab185" />

<img width="320" alt="image" src="https://github.com/user-attachments/assets/6dc268c2-2fa0-4af5-ade7-8f54e2db13b1" />

**Comment by FixResolution** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by haykgalstyan** [comment]
I am reporting an issue. Please let me know if I can help with more details.

**Comment by FixResolution** [comment]
> I am reporting an issue. Please let me know if I can help with more details.

Kindly reach out to the above help center via the link

**Comment by haykgalstyan** [comment]
This is not a help request, but a bug report.

**Comment by quetool** [comment]
Thanks for reporting @haykgalstyan! Solflare wallet it is indeed listed https://walletguide.walletconnect.network/?devices=Mobile&search=solflare, I will ask the team and get back to you.

**Comment by quetool** [comment]
Actually I think I know what's happening. Solflare supports only Solana chains and you are probably adding Ethereum (or other) chains by default.

Can you try to call this `ReownAppKitModalNetworks.removeSupportedNetworks('eip155');` before instantiating `ReownAppKitModal()`? Do the same for every other non-Solana chain if you added it, like `ReownAppKitModalNetworks.removeSupportedNetworks('polkadot');` etc...

**Comment by haykgalstyan** [comment]
Tried both ways (the commented code), but still don't see Solflare.

```
  appkit.ReownAppKitModal _createModalService(UiContext context) {
    appkit.ReownAppKitModalNetworks.removeSupportedNetworks('eip155');
    return appkit.ReownAppKitModal(
      context: context.as<BuildContext>(),
      projectId: _config.projectId,
      metadata: appkit.PairingMetadata(
        name: _config.appInfo.name,
        description: _config.appInfo.description,
        url: _config.appInfo.url,
        icons: [_config.appInfo.iconUrl],
        redirect: appkit.Redirect(
          native: _config.appInfo.redirectNativeScheme,
        ),
      ),
      featuredWalletIds: {
        '1ca0bdd4747578705b1939af023d120677c64fe6ca76add81fda36e350605e79',
      },
      // optionalNamespaces: {
      //   'solana': appkit.RequiredNamespace(
      //     chains: [],
      //     methods: [],
      //     events: [],
      //   ),
      // },
      optionalNamespaces: {
        NetworkNamespace.solana.name: appkit.RequiredNamespace(
          chains: ['solana:EtWTRABZaYq6iMfeYKouRu166VU2xqa1'],
          methods: ['solana_signAndSendTransaction'],
          events: [],
        ),
      },
      ...
```

**Comment by haykgalstyan** [comment]
I think I have tried all the possible setup combinations unfortunately :/ 
Do you see it on your end?

**Comment by quetool** [comment]
Ok indeed something weird is happening with the query on the backend. I'll reach out the team and let you know!

**Comment by haykgalstyan** [comment]
On a separate but related note I have a native crash when scrolling through wallet list on android. Looks like a out of memory error. 

```
15:28:12.176  E  [ERROR:flutter/impeller/renderer/backend/vulkan/command_buffer_vk.cc(106)] Break on 'ImpellerValidationBreak' to inspect point of failure: Failed to end command buffer: ErrorOutOfHostMemory
15:28:12.177  A  Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x38 in tid 26770 (1.raster), pid 26735 (com.mypackagename.app)
15:28:12.444  A  Cmdline: com.mypackagename.app
15:28:12.444  A  pid: 26735, tid: 26770, name: 1.raster  >>> com.mypackagename.app <<<
15:28:12.444  A        #00 pc 00000000020a86a4  /data/app/~~8_tbTNPipd0lHDD6PCmreg==/com.mypackagename.app-0D8oa3pWp2cFJsS80pVMYg==/base.apk!libflutter.so (offset 0x1168000) (BuildId: b0c8ea18145e86f27eccbf0956cff58f847fee5b)
```

**Comment by quetool** [comment]
Regarding Solflare:
There was an issue with their Cloud listing, the team updated it and it should show up for non cached queries (it may take up to 6 hours to fully propagate) to servers.

Regarding the memory issue: Interesting, never saw an out of memory issue before, could you open a separate issue with steps to repro?

**Comment by haykgalstyan** [comment]
Great, thank you!
Will open the other issue later.

**Comment by quetool** [comment]
GM @haykgalstyan! Solflare wallet should be showing up now. Thanks for reporting!

<img src="https://github.com/user-attachments/assets/7a33a17e-ae72-4f4b-bbf4-cda296bb23ee" width="300">

**Comment by haykgalstyan** [comment]
Thanks for the quick fix!

**Comment by haykgalstyan** [comment]
Hello @quetool. 
So the wallet is shown in the listing, but it does not open neither on android nor on iOS giving an error. Other solana wallets like Phantom open without any problems with the same configuration, leading me to believe there may be something else with Solflare cloud listing.

![solflare_error_ios](https://github.com/user-attachments/assets/f2b42306-1749-4fb9-85eb-34de0f67a3bd)
![solflare_error_android](https://github.com/user-attachments/assets/79ef81b2-77a5-4e28-8cb7-b94b598269cd)

**Comment by haykgalstyan** [comment]
This is the error I get on callback onModalError. Nothing useful

```
ModalError(message: Unable to open Wallet app)
```

**Comment by haykgalstyan** [comment]
Debugging let me here if this will help
<img width="1404" alt="image" src="https://github.com/user-attachments/assets/afc3e41a-b937-46fd-953e-3dc53255a845" />

**Comment by quetool** [comment]
I'll check this, thanks!

**Comment by haykgalstyan** [comment]
Oh... got it.
In the WalletGuide it says that Phantom does only support mainnet and not devnet on mobile, what would be a popular solana wallet that works with WalletConnect protocol?

**Comment by quetool** [comment]
Here there are the wallets that supports Solana with WalletConnect on mobile https://walletguide.walletconnect.network/?devices=Mobile&chains=solana%3A5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp
We are working on supporting Phantom as we speak.

**Comment by haykgalstyan** [comment]
Yes, the problem is devnet, when I enable that in the filter not much comes up...
But awesome news on Phantom, crossing my fingers on that :)

**Comment by quetool** [comment]
Hello @haykgalstyan ! Phantom Wallet is now supported in beta in version `^1.4.0-beta01`!

**Comment by haykgalstyan** [comment]
Thats great news, thanks for letting me know! Will check it out soon

**Comment by quetool** [comment]
Hello @haykgalstyan! Solflare wallet support has just landed on AppKit on latest version! Check it out! 
https://pub.dev/packages/reown_appkit/changelog
